version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  redis:
    image: redis
    ports:
        - 6379:6379
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    depends_on:
      - php-prometheus
    volumes:
      - ./docker/prometheus/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/prometheus/index.php:/var/www/public/index.php
  php-prometheus:
    build:
      context: .
      dockerfile: docker/prometheus/Dockerfile
    volumes:
      - ./:/var/www/public
    depends_on:
      - redis
      - prometheus